### ISSUE TITLE
Update Go extension dependency

### ISSUE THREAD

**Issue by hyangah** [ITMCdev/vscode-extensions#20]
The [ms-vscode.Go](https://github.com/microsoft/vscode-go) extension has migrated to [golang.Go](https://marketplace.visualstudio.com/items?itemName=golang.Go) (https://github.com/microsoft/vscode-go/issues/3247). See more details [on our blog post](https://golang.blog/vscode-go). 

Please update your dependency on this extension to `golang.Go`.

**Comment by dragoscirjan** [comment]
@hyangah  Thank you for letting me know. Will schedule a maintenance task, to update this and a few other extensions :).

**Comment by dragoscirjan** [comment]
@hyangah Again thank you for letting me know. I've updated our extension.
